# Generated by Django 5.2.6 on 2025-09-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectLab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahasiswa',
            name='jurusan',
            field=models.CharField(default='Teknik Informatika', max_length=255),
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='nim',
            field=models.CharField(default=1, max_length=10),
        ),
    ]
